### ISSUE TITLE
#24번 문제에서는 command.sh를 저희가 만들어야 하는건가요?

### ISSUE THREAD

**Issue by jsrimr** [zzsza/shell-scripts#1]
쉘스크립트 연습하고 싶어서 따라해보려고 하는데 24번 문제를 풀라고 지시를 받았지만, 뭘해야하는지 모르겠습니다~

**Comment by zzsza** [comment]
안녕하세요-!

24번의 경우 서브셸의 활용법에 대해 정리한 스크립트고, command.sh은 어떤 내용이어도, 서브셸이 작동한 후, 본래 폴더로 돌아간다는 의미를 가지고 있습니다

이 레포는 제가 누군가를 위해서 만든 레포가 아닌 제가 사용한 스크립트를 하나씩 정리하는 용도입니다.
따라서 따라하시려고 하시면 어려움이 약간 존재할수도 있을 것 같습니다-!

"문제를 풀어보세요"가 나오는 스크립트는 나중에 제가 파일명만 보고 해당 내용을 작성하도록 만든거라(=친절한 설명이 없는 편이라..) 어려울 수 있을 것 같아요.. ;ㅁ;

관심 가져주셔서 감사합니다!
